# Generated by Django 5.0.8 on 2024-09-26 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogtagindexpage"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="feed_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="private_field",
            field=models.CharField(default="Default private value", max_length=255),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="blogpagegalleryimage",
            name="private_field",
            field=models.CharField(default="Default private value", max_length=255),
        ),
    ]
